### PR TITLE
Print reason if chrome.Driver::get rejects.

### PR DESCRIPTION
**Pull request by wh0**

### CODE REVIEW

**Comment by mitar** [comment]
LGTM.

**Comment by mitar** [comment]
Hm, but check that this is really their promise API. :-)

**Comment by mitar** [comment]
:information_source: https://code.google.com/p/selenium/wiki/WebDriverJs#Promises

**Comment by mitar** [comment]
> If a rejected promise is left unhandled, the offending error will be passed to the active control flow in the next turn of the JavaScript event loop. You can receive notifications of unhandled rejections by listening for an "uncaughtException" event on the ControlFlow object:
> If no event listeners have been registered, the ControlFlow will rethrow the error to the global error handler. In Node.js, this will trigger an "uncaughtException" event on the global process object; in a browser, window.onerror will be notified. 

It seems it would throw an exception anyway, so no need for this change?

**Comment by wh0** [comment]
ha, yeah I guess not.

**Pull request closed without merging**
